### ISSUE TITLE
part message ???

### ISSUE THREAD

**Issue by RichGriese** [fumieval/discord-vc-notification#10]
Not sure if there is a part message available as well as a join message and I'm simply overlooking it. But... if not, you might consider adding a part message as well.

Here's is how I'm thinking that would be useful. I have a voice channel that is listen only that has a bot that plays various content 24/7. The vc-notification bot seems like it would be useful to help members get a sense for who is actually listening to the content. So let's call the channel I post the vc-notifications into "the log channel". If a member looks at the log channel and sees someone comes in once, that tells them something. If they also see they come in every day, that tells them more (ie, the person is active), but a person could just enter and exist the VC every day quickly. But if the log channel shows the person enters, stays for 30 minutes and then parts, it indicates the person is probably sticking around to actually listen to the content. So, without a bot message indicating when someone parts, it's tough for members to tell the difference between the 2nd & 3rd type of person.

Enjoy life!

PS... the link to profile change was really helpful as you can see in the above scenario. Once a member sees someone in the log channel they might want to reach out to, they can now click on their Discord profile, and quickly see if that person also has their Twitter account attached to their Discord profile, and easily click on that, to view the type of tweets they make to decide if this is the type of person that shares their interests, and might be someone they want to reach out to, and can now easily do so.

---

**Comment by fumieval** [comment]
I deliberately avoided sending notification when people leave, because the frequency of messages is a problem already.

**Comment by RichGriese** [comment]
Right on... I understand. Enjoy life!
