### ISSUE TITLE
Notifications not displaying names sometimes

### ISSUE THREAD

**Issue by KorvJonas** [fumieval/discord-vc-notification#8]
The bot is working great, but I noticed something happening awhile back, sometimes when people join it doesn't state their name.
The only thing all these people seem to have in common is that they aren't using a custom picture on discord, they are using the standard picture discord provides.
Discord standard picture:
![image](https://user-images.githubusercontent.com/77399864/111036653-8cbdc900-8420-11eb-909f-1cc4b1b92397.png)

And here is a picture that showcases what I'm talking about:
![image](https://user-images.githubusercontent.com/77399864/111036848-a6134500-8421-11eb-90a0-45acc3058219.png)

**Comment by fumieval** [comment]
I deployed a new version. Now it should display the initial icons correctly
