### ISSUE TITLE
clickable name on the joined message

### ISSUE THREAD

**Issue by RichGriese** [fumieval/discord-vc-notification#9]
Cool bot! 

It would be even better if you would make the name that joins the voice channel in the message, clickable to the users profile. Similar to when you click on someone's name in the sidebar or when they post a message.

I know when they are in the voice channel they will appear on the channel and you can navigate over and click there... but... let's say they pop in the voice channel, and then pop out... and you got a server with 1000 members and the person's status is offline... it's gonna be a nightmare to try to find that person in the right hand sidebar later. But... if the join message was clickable, you'd be able to view their profile right from the channel you are logging joins to.

Enjoy life!

---

**Comment by fumieval** [comment]
I added a link to the user to the notification message. It looks like
![Screenshot from 2021-04-27 13-07-19](https://user-images.githubusercontent.com/761865/116183834-a1002000-a759-11eb-9e77-d9f9d1c79bd5.png)

**Comment by RichGriese** [comment]
Very cool! I tested it, and it works like a charm. That was pretty damn quick. Thanks!
